models/course.py
#کتاب خانه ها 

from sqlalchemy import *

from extentions import db 

#دیتابیس 


class Course(db.Model):
    __tablename__="courses"
    id = Column(Integer , primary_key= True)
    name = Column(VARCHAR, unique=True, index=True , nullable=False)
    description = Column(VARCHAR, unique=True, index=True , nullable=False)
    teacher = Column(VARCHAR,nullable=True,index=True)
    price = Column (String,index=True,nullable=False)
    active = Column(Integer)

models/product.py
#کتاب خانه ها 
from sqlalchemy import *
from extentions import db 

#دیتابیس 


class Product(db.Model):
    __tablename__="products"
    id = Column(Integer , primary_key= True)
    name=Column(String,unique=True,nullable=False,index=True)
    description=Column(String ,nullable=False,index=True)
    quantity=Column(Integer,nullable=False , index=True)
    price=Column(String ,nullable=False, index=True)
    active = Column(INTEGER)

blueprints/general.py
# کتاب خانه ها 

from flask import Blueprint , request , render_template 

#فایل ها

from models.product import *

from models.course import *

from models.exprience import *

app = Blueprint('general',__name__)


@app.route('/', methods=["GET"])
def main():
    if request.method == "GET":
        courses = Course.query.filter(Course.active==1).order_by(func.random()).limit(6).all()
        experiences = Experience.query.filter(Experience.active ==1).order_by(func.random()).limit(5).all()
    return render_template('main.html', courses = courses , experiences = experiences)


@app.route('/courses', methods=["GET"])
def courses():
    if request.method == "GET":
        courses = Course.query.filter(Course.active == 1).all()
    return render_template('courses.html', courses = courses)


@app.route('/experiences', methods=["GET"])
def experiences():
    if request.method == "GET":
        experiences = Experience.query.filter(Experience.active == 1).all()
    return render_template('experiences.html', experiences = experiences)



@app.route('/course/<int:id>/<name>',methods=["GET"])
def course(id,name):
    course = Course.query.filter(Course.id == id).filter(Course.name == name).filter(Course.active==1).first_or_404()
    another_course = Course.query.order_by(func.random()).limit(3).all()
    return render_template('course.html',course=course,another_course=another_course)


@app.route('/experience/<int:id>/<name>',methods=["GET"])
def experience(id,name):
    experience = Experience.query.filter(Experience.id == id).filter(Experience.name == name).filter(Experience.active==1).first_or_404()
    another_experience = Experience.query.order_by(func.random()).limit(3).all()
    return render_template('experience.html',experience=experience,another_experience=another_experience)

templates/parts/course.html
<article class="course-box">
    <a href="{{ url_for('general.course' , id=c.id , name=c.name)}}">
        <img class="course-cover" src="{{url_for('static',filename='covers/course/'+c.id|string+ '.jpg')}}">  
        <h3 class="course-title">{{c.name}}</h3> 
        <div class="course-box-desc">
            {{c.description |truncate(100)}}
        </div> 
        <hr>
        <div class="course-bottom-box">
            <div class="course-deteail-2">
                <h5 class="course-teacher">{{c.teacher}}</h5>
            </div>
            <div>
                <div class="course-price price-toman">{{c.price}}</div>
            </div>
        </div>
    </a>
</article>

templates/parts/experience.html
<article class="blog-box">
    <a href="{{ url_for('general.experience' , id=e.id , name=e.name)}}">
        <img class="blog-cover" src="{{url_for('static',filename='covers/experience/'+e.id|string+ '.jpg')}}">  
        <div class="blog-descr">
            <a href="{{ url_for('general.experience' , id=e.id , name=e.name)}}">
                <h3>{{e.name}}</h3>
                <p>{{e.description | truncate(400)}}</p>
            </a>
            <a class="a" href="{{ url_for('general.experience' , id=e.id , name=e.name)}}">ادامه مطلب </a>
        </div> 
    </a>
</article>

templates/parts/footer.html
<footer>
    <section class="footer">
        <section style="max-width:350px;">
            <h3>لینک‌های مفید</h3>
            <section class="link-list" style="max-width: 250px;min-width: 210px;padding-right: 5px;">
                <a href="/courses" title="آموزش های برودکست">دوره های آموزشی</a>
                <a href="/experiences" title="تجربه های بروکست">تجربه ها</a>
                <a href="/blog" title="مقاله های آموزشی برودکست">مقاله‌های آموزشی</a>
            </section>
        </section>
        <section style="max-width: 350px">
            <h3>تماس با ما</h3>
            <section class="flex linkbox" style="max-width: 250px;">
                <div class="inline flex-box header-link" style="width: 170px;direction: ltr;margin-bottom: 0;">
                    <a href="https://wa.me/+989123456789" style="text-decoration: none;color:black;" target="_blank" title="پشتیبانی در واتساپ">
                        <div class="flex2" style="padding: 5px">
                            <img src="/static/default/Wh.png" class="icon" alt="پشتیبانی در واتساپ">
                            <h4>0912 34 56 789</h4>
                        </div>
                    </a>
                </div>
    
                <div class="inline flex-box header-link" style="width: 170px;direction: ltr;margin-bottom: 0;">
                    <a href="https://wa.me/+989214269672" style="text-decoration: none;color:black;" target="_blank" title="پشتیبانی در واتساپ">
                        <div class="flex2" style="padding: 5px">
                            <img src="/static/default/Wh.png" class="icon" alt="پشتیبانی در واتساپ">
                            <h4>0921 98 76 543</h4>
                        </div>
                    </a>
                </div>
    
                <div class="inline flex-box header-link" style="width: 170px;direction: ltr;margin-bottom: 0;">
                    <a href="https://telegram.me/broadcast_support" style="text-decoration: none;color:black;" target="_blank" title="پشتیبانی در تلگرام">
                        <div class="flex2" style="padding: 5px">
                            <img src="/static/default/tel.png" class="icon" alt="پشتیبانی در تلگرام">
                            <h4>0912 34 56 789</h4>
                        </div>
                    </a>
                </div>
    
    
                <div class="inline flex-box header-link" style="width: 170px;direction: ltr;margin-bottom: 0;">
                    <a href="https://telegram.me/broadcast_support2" style="text-decoration: none;color:black;" target="_blank" title="پشتیبانی در تلگرام">
                        <div class="flex2" style="padding: 5px">
                            <img src="/static/default/tel.png" class="icon" alt="پشتیبانی در تلگرام">
                            <h4>0921 98 76 543</h4>
                        </div>
                    </a>
                </div>
    
    
            </section>
        </section>
        <section style="max-width: 350px">
            <h3>شبکه های اجتماعی</h3>
            <section class="flex linkbox" style="max-width: 250px;">


                <div class="inline flex-box header-link">
                    <a href="https://instagram.com/broadcast_home" style="text-decoration: none;color:black;" target="_blank" title="اینستاگرام خانه برودکست">
                        <div class="flex2" style="padding: 5px">
                            <img src="/static/default/instagram.png" class="icon" alt="اینستاگرام خانه برودکست">
                            <h4>اینستاگرام</h4>
                        </div>
                    </a>
                </div>
                <div class="inline flex-box header-link">
                    <a href="https://www.youtube.com/@broadcast_home" style="text-decoration: none;color:black;" target="_blank" title="خانه برودکست در یوتیوب">
                        <div class="flex2">
                            <img src="/static/default/youtube.png" class="icon" alt="خانه برودکست در یوتیوب">
                            <h4>یوتیوب</h4>
                        </div>
                    </a>
                </div>
                <div class="inline flex-box header-link">
                    <a href="#" style="text-decoration: none;color:black;" target="_blank" title="تلگرام خانه برودکست">
                        <div class="flex2">
                            <img src="/static/default/tel.png" class="icon" alt="تلگرام خانه برودکست">
                            <h4>تلگرام</h4>
                        </div>
                    </a>
                </div>
            </section>
        </section>
    </section>
    <hr style="margin: 10px auto;max-width:1200px;">
    <section>
        <div style="display: flex;flex-flow: wrap;align-items: center;justify-content: center;max-width: 620px ;margin: auto;">
            <img class="logo-footer" src="/static/default/5.png" alt="خانه برودکست">
            <p style="max-width: 500px;font-size: 16px;text-align: justify;padding: 5px 5px;">
                "با بیش از 20 سال تجربه در حوزه برودکست و آموزش‌های مرتبط، من از افتخار می‌برم که دوره‌های آموزشی خود را با شما به اشتراک بگذارم. از مباحث مقدماتی تا مفاهیم پیشرفته، ما تضمین می‌کنیم که تمامی دوره‌هایمان توسط صاحبان تجربه و متخصصان ارائه شده و به شما کمک می‌کنند تا به تخصص و دانش خود افزوده و به دنبال رشد و پیشرفت حرفه‌ای خود باشید. با ما همراه باشید و دنیای برودکست را به همراه هم کشف کنیم."
            </p>
        </div>
    </section>
    <section style="text-align: center;margin-top: 20px;background: var(--bgmp-color);padding: 10px;">
        <h6 style="color: var(--mainlop-color);">کلیه حقوق مادی و معنوی برای خانه برودکست محفوظ است</h6>
    </section>
    <div class="whatsapp-contact" style="bottom: 90px;">
        <a href="https://t.me/broadcast_support" title="تماس با خانه برودکست" target="_blank">
            <img src="/static/default/tel.png">
        </a>
    </div>
    <span class="whatsapp-tooltip">مشاوره رایگان</span>
    <div class="whatsapp-contact">
        <a href="https://wa.me/+9123456789" title="تماس با خانه برودکست" target="_blank">
            <img src="/static/default/Wh.png">
        </a>
    </div>
</footer>

templates/parts/header-animation.html
<section class="header-animation">
    <div style="text-align: right ;">
        <h1 class="home-animation"> به دنیای برودکست خوش آمدید ! </h1>
        <h4 class="home-animation">از مبتدی تا حرفه‌ای، اکتشاف کنید</h4>
        <h6 class="home-animation">همراهی ما ، تضمینی برای رشد شماست</h6>
        <div class="neon-btn"style="width: 180px;margin-right: 5px;">
            <a href="#" title="از اینجا شروع کن" >مشاوره رایگان ...</a>
        </div> 
    </div>
    <div style="min-width: 300px ;">
        <img src="/static/default/1703613325941.png" style="max-width: 570px;width: 100%;">
    </div>
</section>

templates/parts/header.html
<nav class="navbar">
    <a href="/" class="logo">برودکست ایران</a>
    <div class="nav-links">
        <ul>
            {% if request.endpoint.startswith("admin") %}
            <li><a href="#">مقاله ها</a></li>
            <li><a href="#">دوره ها</a></li>
            <li><a href="#">محصول ها</a></li>
            <li><a href="#">تجربه ها</a></li>
            {%else%}
            <li class="active"><a href="/">خانه</a></li>
            <li><a href="/courses">دوره ها</a></li>
            <li><a href="/experiences">تجربه ها</a></li>
            {% if current_user.is_authenticated %}
            <li><a href="#">پنل کاربری</a></li>
            {%endif%}
            <li><a href="/user/login">ثبت نام/ورود</a></li>            
            <li><a href="#">پشتیبانی</a></li>
        {%endif%}
        </ul>
    </div>
    <img src="/static/logo/menu.png" alt="menu hamburger" class="menu-hamburger">
</nav>
<script>
    const menuHamburger = document.querySelector(".menu-hamburger")
    const navLinks = document.querySelector(".nav-links")

    menuHamburger.addEventListener('click',()=>{
    navLinks.classList.toggle('mobile-menu')
    })
</script>
<header>
</header>

templates/parts/product.html
<div >
    <a  href="{{ url_for('general.product' , id=p.id , name=p.name) }}">
        <section>
            <div>    
                <img src="{{url_for('static',filename='covers/product/'+p.id|string+ '.jpg')}}">   
                <h3>{{p.name | truncate(40)}}</h3>
                <p>{{p.description|truncate(60)}}</p>
                <span >{{p.price}}</span>
            </div>
        </section>
    </a>
        <a class="add-to-cart" href="/add-to-cart?id={{p.id}}"> افزودن به سبد</a>
</div>